spring:
  jackson:
     time-zone: GMT+8
     date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
# LOGGING 
logging:
  file: D:\\logs\myspringboot.log    #
#  path: 
  level: 
    com.example.ms_demo: debug 
  
---
spring:
  profiles: local
  datasource:
    name: test
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源

#    HTTP ENCODING  
security:
  user:
    name: aaa
    password: bbb
  basic:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://aaa:bbb@localhost:8761/eureka/

---
spring:
  profiles: dev
  datasource:
    name: test
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.60.50.25:3306/test?characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源

#    HTTP ENCODING  
security:
  user:
    name: aaa
    password: bbb
  basic:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://aaa:bbb@localhost:8761/eureka/

  

  
  
  
  
  
  
   