spring:
  http:   
    encoding:
      charset: "UTF-8" 
      force: true
      enabled: true
    multipart:
      max-file-size: 30MB        
  thymeleaf:
   cache: false
   prefix: classpath:/templates/
   suffix: .html
   encoding: "UTF-8" 
   enabled: true
   content-type: text/html
   mode: HTML5 
   


  jackson:
     time-zone: GMT+8
     date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: local
# LOGGING 
logging:
  file: /logs/myspringboot.log    #
#  path: 
  level: 
    com.example.ms_demo: debug 
  
---
spring:
  profiles: local
  datasource:
    name: test
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.60.50.25:3306/test?characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源

#    HTTP ENCODING 

  mail:
    protocol: smtp #smtp是邮件发送协议，pop3和imap是邮件接收协议。因为我们要发送邮件，因此是smtp
    host: smtp.qq.com #邮件发送服务器的主机，这里采用的是126邮箱来发送邮件
    port: 465 #邮件发送服务器的端口
    auth: true #一般情况下，发送邮件都是要进行验证
    username: 380328854@qq.com #邮件发送服务器的用户名
    password: CHENJINWEI1990 #密码

 
security:
  user:
    name: aaa
    password: bbb
  basic:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://aaa:bbb@localhost:8761/eureka/

---
spring:
  profiles: dev
  datasource:
    name: test
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.60.50.25:3306/test?characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源

#    HTTP ENCODING  
security:
  user:
    name: aaa
    password: bbb
  basic:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://aaa:bbb@localhost:8761/eureka/

  

  
  
  
  
  
  
   